### PR TITLE
feat: added files to encourage PEP8

### PR DESCRIPTION
**Pull request by ZlaTanskY**
*PROPOSAL*
To have all developers align on codestyle, Python dev's created [PEP8 style guide](https://peps.python.org/pep-0008/).
Some tools to help enforce this guide are included in this PR:
- typecheck (`mypy`)
- docstyle (`pydocstyle`)
- linter (`pylint`)
- codestyle (`pycodestyle`)

By using the `Makefile`, it is easy to perform these checks by running the following command:
`make code-qa`

Similarly the unit tests can be run by running the following command:
`make test-unit`

Other commands can be found and/or added in the `Makefile`.

### CODE REVIEW

**Comment by ZlaTanskY** [comment]
I've not yet worked with `black`, but it could be a replacer for `pylint` if you prefer.
See https://github.com/psf/black

**Comment by sborms** [comment]
Hi @ZlaTanskY, awesome!

Could we go for `black`? That was also the conclusion in #54. I too heard good things about it.

**Comment by ZlaTanskY** [comment]
I have replaced `pylint` with `black` and changed the code accordingly, see https://github.com/PythonPredictions/cobra/pull/132/commits/39a28fbf3cf6111b50eeafc813ca43485b7f37da

I also added the make command `make black-check` which will only check for PEP8 violations and not automatically replace them. This way you still have complete control on what would be changed. If you do like the automatic code replacement, you could always add a make command similar to the existing one and leave out the `--diff` flag.

**Comment by sborms** [comment]
Looks all good to me! Can you make it merge into the develop branch instead of the master? Then I'll approve it right away. The repo is structured as follows: master (released versions) > develop > issue branches. There's some info here: https://github.com/PythonPredictions/cobra/wiki/Contributing-guidelines-&-workflows.

**Pull request merged**
