### PR TITLE
n_bins parameter to Evaluator() to control lift curve computation

### LINKED ISSUE #35: Number of deciles in evaluator plots
Cumulative lift, cumulative response now always show 10 bins (decile), change it to be optional.

- [x] `plot_cumulative_gains()` plot has optional number of bins

- [x] `plot_lift_curve()` has optional number of bins 

- [x]  `plot_cumulative_response_curve()` has optional number of bins

### PR DESCRIPTION
**Pull request by sborms**
fixes #35

- added argument `n_bins` to the `Evaluator()` class, to allow flexibility in terms of choosing the number of lift curve bins to compute and hence plot
- by default argument is at 10, so deciles, meaning nothing changes compared to before if the user ignores the argument

### CODE REVIEW

**Review by JanBenisek — CHANGES_REQUESTED** [review]
Looks good, but please could you add one unit test to see if the function `_compute_lift_per_bin()` really returns as many bins as asked? Might be straightforward, but let's try having a good test coverage, thanks!

**Comment by sborms** [comment]
> Looks good, but please could you add one unit test to see if the function `_compute_lift_per_bin()` really returns as many bins as asked? Might be straightforward, but let's try having a good test coverage, thanks!

Series of small commits but the test is there.

Strange it gives conflicts - all new code is an addition, not a modification. You can resolve using the web editor and merge to develop.

**Review by JanBenisek — APPROVED** [review]

**Comment by JanBenisek** [comment]
@sborms thanks, all good, conflicts resolved (just some small annoyance).
Please do not forget to always add a project label and linked issue (right side).
I also deleted the dev branch from here (remote).

**Review by sandervh14 — COMMENTED** [review]
OK, I went over the code. No comments.

**Pull request merged**
